### ISSUE TITLE
nfl.hpp not found

### ISSUE THREAD

**Issue by tomas-slaninka** [CryptoExperts/FV-NFLlib#4]
Hi guys, I am having a problem when I want to use "make" command. The error is: "fatal error: nfl.hpp: No such file or directory
compilation terminated."

I think I have all required libs installed correctly, do you have any ideas on what is the problem?
Thanks for the answer!

**Comment by tomas-slaninka** [comment]
Ok, I have solved this issue myself - problem was with NFLlib, you have to run something similar to the command "sudo ldconfig /root/nfllib/lib" to link the shared library - NFLlib should be in folder with Documents, Downloads etc. so just get there, go to lib folder and in console call pwd to get full path to the lib folder.
You have to run this command after every restart of OS - there should be some way to make it permanent, but I havent found one yet.

**Comment by tlepoint** [comment]
Yes the library include directory should be included when you compile. Glad you found a way to solve that.
